<template>
  <div class="p-inputgroup py-5">
    <InputText
      v-model="playlistName"
      placeholder="Playlist Name"
      @keyup.enter="savePlaylist"
    />
    <Button
      label="Save and Open"
      severity="info"
      @click="savePlaylist"
      :disabled="playlistName.length === 0"
    />
  </div>
  <div>
    <h3>Playlist Preview</h3>
    <DataTable
      v-if="songStore.playlist.length > 0"
      :value="songStore.playlist"
      tyleStyle="min-width: 50rem"
    >
      <Column field="name" header="Track Name"></Column>
      <Column field="artist" header="Artist"></Column>
    </DataTable>
  </div>
</template>

<script setup>
import { inject, ref } from "vue";
import { useSongsStore } from "../stores/songsStore";
import { useSpotifyTokenStore } from "../stores/spotifyTokenStore";

const handleExpiredToken = inject("handle-expired-token");

const songStore = useSongsStore();
const spotifyTokenStore = useSpotifyTokenStore();

const playlistName = ref("");

const playlistUris = [];
for (const song of songStore.playlist) {
  playlistUris.push(song.trackUri);
}

const savePlaylist = async (event) => {
  if (playlistName.value.length === 0) return;

  const createPlaylistResponse = await fetch(
    `https://api.spotify.com/v1/users/${spotifyTokenStore.myId}/playlists `,
    {
      headers: { Authorization: `Bearer ${spotifyTokenStore.token}` },
      method: "POST",
      body: JSON.stringify({
        name: `${playlistName.value} (${new Date().toJSON()})`,
        description: "Autogenerated Playlist",
        public: true,
        collaborative: false,
      }),
    }
  );
  handleExpiredToken(createPlaylistResponse, spotifyTokenStore);
  const cprJson = await createPlaylistResponse.json();

  const addTracksResponse = await fetch(
    `https://api.spotify.com/v1/playlists/${cprJson.id}/tracks`,
    {
      headers: { Authorization: `Bearer ${spotifyTokenStore.token}` },
      method: "POST",
      body: JSON.stringify({ uris: playlistUris }),
    }
  );
  handleExpiredToken(addTracksResponse, spotifyTokenStore);

  window.open(`https://open.spotify.com/playlist/${cprJson.id}`, "_blank");
};
</script>

<style scoped></style>
