<template>
  <div>
    <a href="https://accounts.spotify.com/authorize?response_type=token&client_id=b5881a3f486f4533803ebdb7263a5996&scope=playlist-modify-public&redirect_uri=http%3A%2F%2Flocalhost%3A8080">
      Log in
    </a>
    <p>
      UserId: {{ userId }}<br/>
    </p>
    <div>
      <label for="track">Track: </label>
      <input v-model="trackSearchTerm" id="track" placeholder="Track or Song Name">
      <p>Track Searched: {{ trackSearchTerm }}</p>
      <p>Track Selected: {{ trackSelected }}</p>
      <p>Saved: <span v-if="saved">SUCCESS!</span></p>

      <label for="playlistName">Playlist Name: </label>
      <input v-model="playlistName" id="playlistName" placeholder="Playlist Name">

      <button v-on:click="doSearch">Search for Track</button>
      <button v-on:click="getRecommendations">Get Recommendations for Selected Track</button>
      <button v-on:click="saveRecommendations">Save Playlist</button>
    </div>
    <div>
      <table>
        <thead>
        <tr>
          <th>Track Name</th>
          <th>Artist</th>
        </tr>
        </thead>
        <tbody>
        <tr v-for="track in tracksFound" v-on:click="selectTrack(track.id)"
            v-bind:class="{ 'trackSelected': (track.id == trackSelected) }">
          <td>{{ track.name }}</td>
          <td>{{ track.artists.map(({name}) => name).join(", ") }}</td>
        </tr>
        </tbody>
      </table>
    </div>
  </div>
</template>

<script>
export default {
  name: 'Home',
  props: {},
  data() {
    return {
      token: "",
      userId: "",
      trackSearchTerm: "Track or Song Name",
      trackSelected: "",
      tracksFound: [],
      playlistName: "",
      saved: false
    }
  },
  created() {
    console.info('Page loaded')
    const self = this;
    const parsedUrl = new URL(window.location.href)
    const hashValue = parsedUrl.hash
    if (hashValue) {
      console.debug('hashValue:', hashValue)
      const hashComponents = hashValue.split("&")
      const tokenComponents = hashComponents[0].split('=')
      this.token = tokenComponents[1]
      console.debug('token:', this.token)

      fetch('https://api.spotify.com/v1/me', {
        headers: {
          "Authorization": "Bearer " + this.token
        }
      })
          .then(response => response.json())
          .then(data => (self.userId = data.id));
    }
  },
  methods: {
    doSearch: function () {
      console.info('Searching for track')
      const self = this;
      const paramString = new URLSearchParams(Object.entries({
        q: this.trackSearchTerm,
        type: "track",
        limit: 5
      })).toString()

      fetch('https://api.spotify.com/v1/search?' + paramString, {
        headers: {
          "Authorization": "Bearer " + this.token
        }
      })
          .then(response => response.json())
          .then(function (data) {
            self.tracksFound = data.tracks.items
          });
    },
    selectTrack(trackId) {
      this.trackSelected = trackId
    },
    getRecommendations: function () {
      console.info('Get recommendations for track: ', this.trackSearchTerm, ' | ', this.trackSelected)
      const self = this;
      const paramString = new URLSearchParams(Object.entries({
        seed_tracks: this.trackSelected,
        limit: 50
      })).toString()

      fetch('https://api.spotify.com/v1/recommendations?' + paramString, {
        headers: {
          "Authorization": "Bearer " + self.token
        }
      })
          .then(response => response.json())
          .then(function (data) {
            console.debug(data.tracks)
            self.tracksFound = data.tracks
          });
    },
    saveRecommendations: function () {
      console.info('Saving recommendations for track: ', this.trackSelected)
      const self = this;
      fetch('https://api.spotify.com/v1/users/' + self.userId + '/playlists', {
        headers: {
          "Authorization": "Bearer " + self.token
        },
        method: "POST",
        body: JSON.stringify({
          name: this.playlistName,
          description: "Autogenerated Playlist",
          public: true,
          collaborative: false
        })
      })
          .then(response => response.json())
          .then(function (data) {
            console.debug('Adding songs to playlist')
            const playlistUris = []
            console.debug(self.tracksFound)

            for (const track of self.tracksFound) {
              console.debug(track)
              playlistUris.push(track.uri)
            }

            fetch('https://api.spotify.com/v1/playlists/' + data.id + '/tracks', {
              headers: {
                "Authorization": "Bearer " + self.token
              },
              method: "POST",
              body: JSON.stringify({
                "uris": playlistUris
              })
            })
                .then(response => response.json())
                .then(data => function(data) {
                  self.saved = true
                });
          });
    }
  }

}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

.trackSelected {
  background-color: aquamarine;
}
</style>
